name: bdqm
services:
  informix:
    image: icr.io/informix/informix-developer-database:14.10.FC9W1DE
    privileged: true
    environment:
      - LICENSE=accept
      - SIZE=small
      - STORAGE=local
    volumes:
      - informix-data:/opt/ibm/data
    healthcheck:
      test: ['CMD-SHELL', 'su - informix -c "/opt/ibm/informix/bin/onstat -" | grep -q "On-Line"']
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 120s
    ports:
      - '9088:9088'
      - '9092:9089'
      - '27017:27017'
      - '27018:27018'
volumes:
  informix-data:
