# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: bdqm
services:
  postgres:
    extends:
      file: postgres.yml
      service: postgres
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  redis:
    extends:
      file: ./redis.yml
      service: redis
  prometheus:
    extends:
      file: ./monitoring.yml
      service: prometheus
  grafana:
    extends:
      file: ./monitoring.yml
      service: grafana
volumes:
  redis-data-bqdm:
  informix-data:
  prometheus-data:
  grafana-data:
